spring:
  application:
    name: spring-boot-api-rest-tienda
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: System
    password: 030903
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.OracleDialect
    show-sql: true
server:
  port: 7575