-- ***  ELIMINA OBJETOS EXISTENTES ***
-- Eliminacion de  triggers
DROP TRIGGER TRG_CATEGORIAS_ID;
DROP TRIGGER TRG_INVENTARIO_ID;
DROP TRIGGER TRG_PROD_FECHA_ACT;
DROP TRIGGER TRG_PRODUCTO_ID;

-- Eliminacion de tablas
DROP TABLE PRODUCTO_CATEGORIAS;
DROP TABLE INVENTARIO;
DROP TABLE CATEGORIAS CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO CASCADE CONSTRAINTS;

-- Eliminacion de secuencias
DROP SEQUENCE SEC_ID_CATEGORIAS;
DROP SEQUENCE SEC_ID_INVENTARIO;
DROP SEQUENCE SEC_ID_PRODUCTO;

-- *** TABLA PRODUCTO ****
CREATE SEQUENCE SEC_ID_PRODUCTO START WITH 1 INCREMENT BY 1;

CREATE TABLE PRODUCTO (
    ID_PRODUCTO NUMBER PRIMARY KEY,
    SKU VARCHAR2(50) UNIQUE NOT NULL,
    NOMBRE VARCHAR2(255) NOT NULL,
    DESCRIPCION CLOB,
    PRECIO NUMBER(10,2) NOT NULL,
    PESO_KG NUMBER(5,2),
    DISPONIBLE CHAR(1) DEFAULT 'Y' NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_ACTUALIZACION DATE,
    URL_IMAGEN VARCHAR2(500)
);

CREATE OR REPLACE TRIGGER TRG_PRODUCTO_ID
BEFORE INSERT ON PRODUCTO
FOR EACH ROW
BEGIN
    :NEW.ID_PRODUCTO := SEC_ID_PRODUCTO.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_PROD_FECHA_ACT
BEFORE UPDATE ON PRODUCTO
FOR EACH ROW
BEGIN
    :NEW.FECHA_ACTUALIZACION := SYSDATE;
END;
/

-- *** TABLA CATEGORIAS ***
CREATE SEQUENCE SEC_ID_CATEGORIAS START WITH 1 INCREMENT BY 1;

CREATE TABLE CATEGORIAS(
    ID_CATEGORIA NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(255) NOT NULL,
    CATEGORIA_PADRE_ID NUMBER,
    CONSTRAINT FK_CATEGORIA_PADRE FOREIGN KEY(CATEGORIA_PADRE_ID) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

CREATE OR REPLACE TRIGGER TRG_CATEGORIAS_ID
BEFORE INSERT ON CATEGORIAS
FOR EACH ROW
BEGIN
    :NEW.ID_CATEGORIA :=SEC_ID_CATEGORIAS.NEXTVAL;
END;
/

-- *** TABLA INVENTARIO ***
CREATE SEQUENCE SEC_ID_INVENTARIO START WITH 1 INCREMENT BY 1;

CREATE TABLE INVENTARIO(
    ID_INVENTARIO NUMBER PRIMARY KEY,
    PRODUCTO_ID NUMBER NOT NULL,
    CANTIDAD_STOCK NUMBER,
    CANTIDAD_RESERVADA NUMBER,
    CONSTRAINT FK_INVENTARIO_PRODUCTO FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE OR REPLACE TRIGGER TRG_INVENTARIO_ID
BEFORE INSERT ON INVENTARIO
FOR EACH ROW
BEGIN
    :NEW.ID_INVENTARIO := SEC_ID_INVENTARIO.NEXTVAL;
END;
/

-- *** TABLA PRODUCTO_CATEGORIAS ***
CREATE TABLE PRODUCTO_CATEGORIAS(
    PRODUCTO_ID NUMBER,
    CATEGORIA_ID NUMBER,
    CONSTRAINT PK_PROD_CAT PRIMARY KEY (PRODUCTO_ID, CATEGORIA_ID),
    CONSTRAINT FK_PRODCAT_PRODUCTO FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(ID_PRODUCTO),
    CONSTRAINT FK_PRODCAT_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

COMMIT;